### PR TITLE
Log error status when SSH terminates during script execution

### PR DESCRIPTION
**Pull request by eradman**
Log error status when SSH terminates during script execution

* log EXEC_ERROR if environment file cannot be updated
* log EXEC_ERROR if ssh(1) returns exit code 255
* log EXEC_ERROR if sh(1) returns exit code 127
* Set log format variable '%e' for connection failures
* Rename RSET_HOST_CONNECT_FAIL to RSET_HOST_CONNECT_ERROR as both error messages may indicate a problem with remote connectivity

### CODE REVIEW

**Comment by vorakl** [comment]
Is it possible to collect that exit status?
Right now, %e returns 0:

```
===> 2024-02-21 15:30:44-0800 rset/4b54af54: ERROR: host=mykube0 exit_code=0
```

```
export RSET_HOST_CONNECT_ERROR="$(echo -e '===> ')$(echo -e '\e[0;36m')%T $(echo -e '\e[1;37m')rset/%s$(echo -e '\e[0m'): $(echo -e '\e[1;31m')ER
ROR$(echo -e '\e[0m'): $(echo -e '\e[0;32m')host$(echo -e '\e[0m')=$(echo -e '\e[1;33m')%h$(echo -e '\e[0m') $(echo -e '\e[0;31m')exit_code$(echo
 -e '\e[0m')=$(echo -e '\e[1;33m')%e$(echo -e '\e[0m')"
```

**Comment by vorakl** [comment]
Just as a side note, it is useful to configure *ConnectTimeout* in the ssh config for the client connections, because if a host is down, it will wait for a long time until actually fail.

**Comment by eradman** [comment]
> Just as a side note, it is useful to configure _ConnectTimeout_ in the ssh config for the client connections, because if a host is down, it will wait for a long time until actually fail.

Yes, this is a very useful parameter to set

**Comment by vorakl** [comment]
It looks great!

image

**Comment by eradman** [comment]
Thanks for testing! As usual the feedback was valuable

**Pull request merged**
