### PR TITLE
Fix a typo in rset(1)

### PR DESCRIPTION
**Pull request by kucharskim**

### CODE REVIEW

**Comment by eradman** [comment]
Thanks for catching that typo. Maybe it would be better to say "executing each script in sequence".

I'm sure there are other flaws in these man pages--please amend this PR with other mistakes or missing details you run across.

**Comment by kucharskim** [comment]
Let me look into it more. Thanks!

**Comment by kucharskim** [comment]
As in, please don't merge yet.

**Comment by eradman** [comment]
I fixed the wording as part of a commit to the NEWS file. Thanks for pointing out this mistake!

**Pull request closed without merging**
