### PR TITLE
Bind miniquark to IPv6 localhost address

### PR DESCRIPTION
**Pull request by adam12**
Fixes issues where the miniquark server is not available through the SSH reverse proxy when connecting to the remote host over IPv6.

Remote OS: Linux
Local OS: MacOS

### CODE REVIEW

**Comment by adam12** [comment]
I tested this with connections over IPv4 as well as IPv6 and they both worked. That said, I'm not actually sure this is a great solution. Modifying miniquark to bind on both interfaces might be better?

**Comment by eradman** [comment]
Thanks for raising this topic @adam12,

It certainly would be better to modify `miniquark` to bind to multiple addresses. Simply resolving all of the addresses for a hostname may suffice:

```
$ host localhost
localhost has address 127.0.0.1
localhost has IPv6 address ::1
```

Then then we would change `127.0.0.1` to `localhost` in `config.h`:

```c
#define INSTALL_URL "http://127.0.0.1:6000"
```

**Comment by adam12** [comment]
> Looking briefly at the source, it seems like miniquark might do it for us if we pass a `localhost` as the bind address.

Unfortunately, this isn't the case. As far as I can tell, we'd need to setup a new socket for IPv6 and then `select(2)` on them for `accept(2)`.

I went to the `quark` upstream repo to see if there had been any support added there, but it looks like it's diverged a lot from the `miniquark` that ships with `rset`.

**Comment by eradman** [comment]
`miniquark` has diverged significantly from `quark`, but I tried a new build of quark and found that it does not listen on all addresses when a hostname is provided either.

I tried `rset` over IPv6 (MacOS -> Ubuntu) and was not able to replicate this issue. What does `netstat | grep 6000` show when run on the remote host?

**Comment by adam12** [comment]
Here's the remote host listening info:

```
tcp   LISTEN 0      128                                                                      127.0.0.1:6000             0.0.0.0:*
tcp   LISTEN 0      128                                                                          [::1]:6000                [::]:*
```

That said, I've just tested it again and everything appears to be working correctly now. I'm not sure what's changed, if anything. Ghost in the machine?

Thanks for checking. Let's close this for now.

**Pull request closed without merging**
